# Generated by Django 5.0.2 on 2024-02-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charcode", models.CharField(max_length=5)),
                ("rate", models.FloatField()),
                ("current_date", models.DateField(db_index=True)),
            ],
        ),
    ]
